import pytest

from datapilot.sql_validator import validate_sql

ALLOWED_TABLES = {
    "dbo.Schools",
    "dbo.Students",
    "dbo.Exams",
    "dbo.Registrations",
    "dbo.Payments",
    "dbo.Results",
}

MUST_PASS = [
    "SELECT COUNT(*) FROM dbo.Students",
    "SELECT COUNT(*) FROM Students",
    "select count(*) from DBO.STUDENTS",
    "SELECT * FROM dbo.Students;",
    "SELECT 'DROP TABLE dbo.Students' AS note FROM dbo.Students",
    "SELECT * FROM dbo.Students WITH (NOLOCK)",
    "WITH s AS (SELECT SchoolId FROM dbo.Students) SELECT COUNT(*) FROM s",
    "SELECT City FROM dbo.Schools UNION SELECT FirstName FROM dbo.Students",
    "SELECT * FROM dbo.Students WHERE SchoolId IN (SELECT SchoolId FROM dbo.Schools)",
    # SQL generated by Gemini in Milestone 5. Q3, Q4 and Q6 are *wrong* answers,
    # but they are safe, so validation must accept them: validity is not correctness.
    "SELECT COUNT(StudentId) FROM dbo.Students",
    "SELECT COUNT(T1.StudentId) FROM dbo.Students AS T1 INNER JOIN dbo.Schools AS T2 "
    "ON T1.SchoolId = T2.SchoolId WHERE T2.City = 'Coimbatore'",
    "SELECT TOP 1 T2.SchoolName FROM dbo.Results AS T1 INNER JOIN dbo.Registrations AS T3 "
    "ON T1.RegistrationId = T3.RegistrationId INNER JOIN dbo.Students AS T4 "
    "ON T3.StudentId = T4.StudentId INNER JOIN dbo.Schools AS T2 ON T4.SchoolId = T2.SchoolId "
    "INNER JOIN dbo.Exams AS T5 ON T3.ExamId = T5.ExamId WHERE T5.ExamYear = 2026 "
    "GROUP BY T2.SchoolName ORDER BY AVG(T1.Score) DESC",
    "SELECT TOP 5 T1.StudentId, T1.FirstName, T1.LastName, T3.Score FROM dbo.Students AS T1 "
    "INNER JOIN dbo.Registrations AS T2 ON T1.StudentId = T2.StudentId "
    "INNER JOIN dbo.Results AS T3 ON T2.RegistrationId = T3.RegistrationId "
    "INNER JOIN dbo.Exams AS T4 ON T2.ExamId = T4.ExamId WHERE T4.ExamYear = 2025 "
    "ORDER BY T3.Score DESC;",
    "SELECT COUNT(DISTINCT T1.StudentId) FROM dbo.Students AS T1 "
    "INNER JOIN dbo.Registrations AS T2 ON T1.StudentId = T2.StudentId "
    "INNER JOIN dbo.Exams AS T3 ON T2.ExamId = T3.ExamId "
    "WHERE T3.ExamYear = 2026 AND T2.Status = 'Absent';",
    "SELECT TOP 12 COUNT(T1.RegistrationId) FROM dbo.Registrations AS T1 "
    "INNER JOIN dbo.Exams AS T2 ON T1.ExamId = T2.ExamId WHERE T2.ExamYear = 2026 "
    "GROUP BY YEAR(T1.RegisteredAt), MONTH(T1.RegisteredAt) "
    "ORDER BY YEAR(T1.RegisteredAt), MONTH(T1.RegisteredAt);",
]

MUST_BLOCK = [
    ("DELETE FROM dbo.Students", "writes data"),
    ("UPDATE dbo.Students SET CurrentGrade = 1", "writes data"),
    ("INSERT INTO dbo.Schools (SchoolName) VALUES ('x')", "writes data"),
    ("MERGE dbo.Students AS t USING dbo.Schools AS s ON 1 = 0 "
     "WHEN NOT MATCHED THEN INSERT (SchoolId) VALUES (s.SchoolId);", "writes data"),
    ("DROP TABLE dbo.Students", "DDL"),
    ("TRUNCATE TABLE dbo.Students", "DDL"),
    ("CREATE TABLE dbo.Hack (a INT)", "DDL"),
    ("ALTER TABLE dbo.Students ADD Hack INT", "DDL"),
    ("GRANT SELECT ON dbo.Students TO public", "permissions"),
    ("SELECT 1; DROP TABLE dbo.Students", "stacked statements"),
    ("SELECT * FROM dbo.Students; SELECT * FROM dbo.Schools", "more than one statement"),
    ("WITH x AS (SELECT 1 AS a) DELETE FROM dbo.Students", "CTE hiding a DELETE"),
    ("SELECT * INTO dbo.Copy FROM dbo.Students", "SELECT INTO creates a table"),
    ("EXEC xp_cmdshell 'dir'", "runs OS commands"),
    ("WAITFOR DELAY '01:00:00'", "denial of service"),
    ("DECLARE @x INT; SELECT @x", "procedural code"),
    ("SELECT * FROM OPENROWSET('SQLNCLI', 'Server=x;Trusted_Connection=yes;', 'SELECT 1')",
     "external data access"),
    ("SELECT * FROM OPENQUERY(LinkedServer, 'SELECT 1')", "linked server access"),
    ("SELECT * FROM sys.sql_logins", "security metadata"),
    ("SELECT * FROM dbo.Students WHERE SchoolId IN (SELECT object_id FROM sys.objects)",
     "system table in a subquery"),
    ("SELECT * FROM OtherDb.dbo.Students", "cross-database"),
    ("SELECT * FROM dbo.Secrets", "table not in the allow-list"),
    ("", "empty"),
    ("   ", "whitespace only"),
    ("this is not sql", "not a SELECT"),
]


@pytest.mark.parametrize("sql", MUST_PASS)
def test_safe_select_is_valid(sql: str) -> None:
    result = validate_sql(sql, ALLOWED_TABLES)
    assert result.is_valid, result.errors


@pytest.mark.parametrize(("sql", "reason"), MUST_BLOCK)
def test_unsafe_sql_is_blocked(sql: str, reason: str) -> None:
    result = validate_sql(sql, ALLOWED_TABLES)
    assert not result.is_valid, f"should be blocked ({reason})"
    assert result.errors


def test_reports_tables_actually_used() -> None:
    result = validate_sql(
        "WITH s AS (SELECT SchoolId FROM Students) "
        "SELECT * FROM s JOIN dbo.Schools sc ON sc.SchoolId = s.SchoolId",
        ALLOWED_TABLES,
    )
    assert result.tables == ["dbo.schools", "dbo.students"]


def test_collects_all_errors() -> None:
    result = validate_sql("SELECT * INTO dbo.Copy FROM sys.objects", ALLOWED_TABLES)
    assert len(result.errors) >= 2
